### ISSUE TITLE
Error occurred while enabling ItemEditor 2 v2.0.0 on 1.20.1 server

### ISSUE THREAD

**Issue by Chevels** [Dumphey/item-editor#5]
Hi !
Since my server went to 1.20.1, with version 2.0.0 of ItemEditor 2, the plugin no longer starts at all and gives this error at startup:

```
[05:03:57] [Server thread/INFO]: [ItemEditor] Enabling ItemEditor v2.0.0
[05:03:57] [Server thread/INFO]: [ItemEditor] Detected major version 20 and minor version 1
[05:03:57] [Server thread/INFO]: [ItemEditor] Reloading items.
[05:03:57] [Server thread/ERROR]: Error occurred while enabling ItemEditor v2.0.0 (Is it up to date?)
java.lang.IllegalArgumentException: Length of Base64 encoded input string is not a multiple of 4.
	at org.yaml.snakeyaml.external.biz.base64Coder.Base64Coder.decode(Base64Coder.java:238) ~[snakeyaml-2.0.jar:?]
	at org.yaml.snakeyaml.external.biz.base64Coder.Base64Coder.decodeLines(Base64Coder.java:199) ~[snakeyaml-2.0.jar:?]
	at at.dumphey.itemeditor.itemeditor.storage.ItemStorage.deserializeItem(ItemStorage.java:103) ~[ItemEditor 2.0 (mc 1.20.x & older).jar:?]
	at at.dumphey.itemeditor.itemeditor.storage.ItemStorage.loadItem(ItemStorage.java:58) ~[ItemEditor 2.0 (mc 1.20.x & older).jar:?]
	at at.dumphey.itemeditor.itemeditor.storage.ItemStorage.reload(ItemStorage.java:37) ~[ItemEditor 2.0 (mc 1.20.x & older).jar:?]
	at at.dumphey.itemeditor.ItemEditor.onEnable(ItemEditor.java:31) ~[ItemEditor 2.0 (mc 1.20.x & older).jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-167]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-167]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.20.1.jar:git-Paper-167]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:551) ~[paper-1.20.1.jar:git-Paper-167]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-167]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[paper-1.20.1.jar:git-Paper-167]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-167]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.1.jar:git-Paper-167]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-167]
	at java.lang.Thread.run(Thread.java:857) ~[?:?]
[05:03:57] [Server thread/INFO]: [ItemEditor] Disabling ItemEditor v2.0.0
```
Where can this come from ?

**Server infos:**
- Paper version git-Paper-167 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 0c0a480)
- Java 17 OpenJ9

**Comment by Dumphey** [comment]
Should be fixed in the newest update - please check!

**Comment by Chevels** [comment]
Hi ! Thank you very much for the update, but unfortunately it still doesn't work :/

Here is the error message:

`[05:00:40] [Server thread/INFO]: [ItemEditor] Enabling ItemEditor v2.0.1
[05:00:40] [Server thread/INFO]: [ItemEditor] Detected major version 20 and minor version 1
[05:00:40] [Server thread/INFO]: [ItemEditor] Reloading items.
[05:00:40] [Server thread/ERROR]: Error occurred while enabling ItemEditor v2.0.1 (Is it up to date?)
java.lang.IllegalArgumentException: Illegal base64 character 3a
	at java.util.Base64$Decoder.decode0(Base64.java:848) ~[?:?]
	at java.util.Base64$Decoder.decode(Base64.java:566) ~[?:?]
	at java.util.Base64$Decoder.decode(Base64.java:589) ~[?:?]
	at at.dumphey.itemeditor.itemeditor.storage.ItemStorage.deserializeItem(ItemStorage.java:113) ~[ItemEditor-2.0.1.jar:?]
	at at.dumphey.itemeditor.itemeditor.storage.ItemStorage.loadItem(ItemStorage.java:58) ~[ItemEditor-2.0.1.jar:?]
	at at.dumphey.itemeditor.itemeditor.storage.ItemStorage.reload(ItemStorage.java:37) ~[ItemEditor-2.0.1.jar:?]
	at at.dumphey.itemeditor.ItemEditor.onEnable(ItemEditor.java:31) ~[ItemEditor-2.0.1.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-194]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-194]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.20.1.jar:git-Paper-194]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:551) ~[paper-1.20.1.jar:git-Paper-194]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.20.1.jar:git-Paper-194]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.20.1.jar:git-Paper-194]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-194]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.20.1.jar:git-Paper-194]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-194]
	at java.lang.Thread.run(Thread.java:857) ~[?:?]
[05:00:40] [Server thread/INFO]: [ItemEditor] Disabling ItemEditor v2.0.1`

**Comment by Chevels** [comment]
> Should be fixed in the newest update - please check!

Any news ? (see my post above)

**Comment by Chevels** [comment]
@Dumphey 

Hello :)
Any news ? (see my post above)

**Comment by Chevels** [comment]
Hello,
issue is still here :/

```
[05:00:38] [Server thread/INFO]: [ItemEditor] Enabling ItemEditor v2.0.2
[05:00:38] [Server thread/INFO]: [ItemEditor] Detected minecraft 1.20.6
[05:00:38] [Server thread/INFO]: [ItemEditor] Reloading items.
[05:00:38] [Server thread/ERROR]: Error occurred while enabling ItemEditor v2.0.2 (Is it up to date?)
java.lang.IllegalArgumentException: Illegal base64 character 3a
	at java.base/java.util.Base64$Decoder.decode0(Base64.java:852) ~[?:?]
	at java.base/java.util.Base64$Decoder.decode(Base64.java:570) ~[?:?]
	at java.base/java.util.Base64$Decoder.decode(Base64.java:593) ~[?:?]
	at ItemEditor 2.0.2 (1.21).jar/at.dumphey.itemeditor.itemeditor.storage.ItemStorage.deserializeItem(ItemStorage.java:113) ~[ItemEditor 2.0.2 (1.21).jar:?]
	at ItemEditor 2.0.2 (1.21).jar/at.dumphey.itemeditor.itemeditor.storage.ItemStorage.loadItem(ItemStorage.java:58) ~[ItemEditor 2.0.2 (1.21).jar:?]
	at ItemEditor 2.0.2 (1.21).jar/at.dumphey.itemeditor.itemeditor.storage.ItemStorage.reload(ItemStorage.java:37) ~[ItemEditor 2.0.2 (1.21).jar:?]
	at ItemEditor 2.0.2 (1.21).jar/at.dumphey.itemeditor.ItemEditor.onEnable(ItemEditor.java:31) ~[ItemEditor 2.0.2 (1.21).jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:1.20.6-138-906df69]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:1.20.6-138-906df69]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:604) ~[paper-1.20.6.jar:1.20.6-138-906df69]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.6.jar:1.20.6-138-906df69]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[paper-1.20.6.jar:1.20.6-138-906df69]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.20.6.jar:1.20.6-138-906df69]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:1.20.6-138-906df69]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-138-906df69]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-138-906df69]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[05:00:38] [Server thread/INFO]: [ItemEditor] Disabling ItemEditor v2.0.2

Server:
Paper version 1.20.6-138-master@906df69 (2024-06-10T06:32:15Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)
```
